### ISSUE TITLE
Problem I don't know what to do

### ISSUE THREAD

**Issue by Hxnis13** [AzizKpln/Bruter19#14]
![Screenshot from 2020-09-13 13-07-29](https://user-images.githubusercontent.com/71214697/93016546-637fc580-f5c2-11ea-92b3-25cba576e049.png)

**Comment by jimisadog** [comment]
having the same problem

**Comment by maxnoyevoy** [comment]
open a new terminal and use these
git clone https://github.com/SusmithKrishnan/torghost.git
cd torghost
chmod +x build.sh
./build.sh

**Comment by AzizKpln** [comment]
i have to update this tool. It doesn't work properly. I will update it after my exams
