### ISSUE TITLE
It Say's Trace Back can you help me fix this? 

### ISSUE THREAD

**Issue by Outsider31** [AzizKpln/Bruter19#16]
![Screenshot_2020-10-31_18-06-54](https://user-images.githubusercontent.com/73740010/97776554-1375b600-1ba4-11eb-9509-4bb143aadb81.png)
BTW i'm using Dual Booted Kali Linux, Main OS is Windows 10.

**Comment by AzizKpln** [comment]
i have to update this tool. It doesn't work properly. I will update it after my exams

**Comment by Outsider31** [comment]
Okay Thanks ^_^
