### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by kaanb585** [AzizKpln/Bruter19#3]
kardeşim yazdıgın brute force programın çok güzel eline sağlık bir sorun olursa yazın demişsin gördüğüm birkaç şeyi söylemek istiyorum. 
1-) bir süre sonra arka arkaya ıp adresi banlandı hatası alıyorum 5-6 kere tekrar ediyor daha sonra şifre bu wordlistin içinde değil diye uyarı verip işlemi sonlandırıyor. wordlistin yarısına bile gelmeden bu hatayı aldım.
2-) açılış biraz yavaş hızlandırırsan mükemmel olur o açılıştaki görsel yüklenmesi biraz sinir etti beni :D 
3-) twitter hesabına saldırı yapmak için mail adresi istiyor saldıracağım kişinin mail adresini bulmanın kolay yolu varsa söyleyebilirmisin? ya da twitter kullanıcı adıyla brute force yapmamız mümkünmü? 
4-) türkiyede yaygın kullanılan wordlist bulmakta zorlanıyorum bulduklarım hep saçma kelimelerle dolu çoğunu boşuna deniyor elinde güzel bi wordlist varsa ulaştırman mümkünmü ?

**Comment by AzizKpln** [comment]
1. Sorununuzun nedeni torghost üst üste ip adresi değiştirirken internet bağlantısı kopmasından kaynaklı olabilir.
2-Güncelleme getirilmesi gerektiğinde açılış hızını da arttırmak için kodları değiştirebilirim.
3-Twitter'a illa mail ile saldırman gerekmiyor kullanıcı adı ile de saldırabilirsin instagramdaki gibi.
4-Wordlist oluşturmak için araçta CUPP aracını kullanıyorum. Elimde belirli bir wordlist yok. 

Zaten bu araç eğlence için geliştirildi. Yani gidip gerçekten birini hacklemen 2020'de brute force ile çok uzak bir ihtimaldir. 2FA'lar olsun, uzun vadeli brute force saldırılarında iplerin banlanması olsun vs. Brute force ile gerçek bir hesap hackleme çok zor artık. Premium proxy kullanarak istediğiniz sonucu elde edebilirsiniz araç ile fakat para vermeden ücretsiz bir şekilde tor network kullanıyorum. O da dediğin hataya yol açabiliyor ona karşı yapabilecek pek bir şeyim yok maalesef.
