### ISSUE TITLE
İlk Kurulumda Karşılaştığım Hata

### ISSUE THREAD

**Issue by BlutBad99** [AzizKpln/Bruter19#4]
Programı indirip, setup.sh dosyası ile kurdum. Kurulum sonunda, tamamlanmadan önce bir hata aldım. " *.spec" isimli bir dosya bulunamadı, uyarısı aldım. Bir sorun olmayacağını düşünüp, brute force saldırısını başlattım. Saldırı başlıyor ama wordlist parolalarını denemeden öylece donmuş gibi duruyordu.

 Sonra yeni bir makine kurup içine yükleme yaptım. "setup.sh" dosyasını çalıştırmadan önce ilgili dosyanın geçtiği komut satırını buldum. Komut, setup.sh dosyası içerisinde 25. Satırda bulunan " rm *.spec " komutu. Ilgili satırı sildim. Kurulumu yeniden yaptım. Sorunsuz bir şekilde çalıştı.

**Comment by AzizKpln** [comment]
Setup.sh'dan gereksiz son satır kodlarını sileceğim fakat hatanın bununla ilgili olduğunu düşünmüyorum çok alakasız :D

**Comment by BlutBad99** [comment]
Bence de alakasız ama sadece o satırı sildiğim için düzelince belki bir
bağlantısı vardır diye düşündüm.

15 Tem 2020 Çar 01:28 tarihinde Aziz Kaplan <notifications@github.com> şunu
yazdı:

**Comment by AzizKpln** [comment]
Tamamdır saol bildirdiğin için

**Comment by yagmurkilic21** [comment]
Programda herşeyi sorunsuz yaptım ama sonunda traceback (most recent call last):
File "bruter19.py" ,line 153, in <module> ....
Böyle birşey çıkıyor yardımcı olu musun?
