### ISSUE TITLE
Sorun

### ISSUE THREAD

**Issue by mrsnake-hack** [AzizKpln/Bruter19#6]
![q](https://user-images.githubusercontent.com/65863021/87848841-d20f1280-c8f4-11ea-9936-63a90a9a0a53.png)

**Comment by AzizKpln** [comment]
sanırım aracı sudo bash install.sh olarak indirdiniz sonra da sudo su ile bruter19 dosyasını çalıştırdınız.
sudo su olarak değil,
sudo python3 bruter19.py şeklinde çalıştırın veya baştan bir kurulum yapın
