### ISSUE TITLE
Çok yavaş

### ISSUE THREAD

**Issue by Muhsinibis** [AzizKpln/Bruter19#7]
Merhaba dostum ellerine sağlık çok güzel bir script yazmışsın fakat program çok yavaş acaba sorun bende mi internetimde mi bilemiyorum. elimde 100binlik bi wordlist var programı 10 saat açık bıraktım ancak sadece 2 bine kadar gelebildi bunu hızlandırmanın bi yolu var mı acaba?

**Comment by AzizKpln** [comment]
2020 yılında 100.000 parola ile sosyal medya hesaplarına saldırı yapamazsınız. Güvenlik önlemleri nedeniyle aracı hızlandıramıyorum. He ücretli bir şekilde günlük proxy alıp onlar üzerinden saldıracağım derseniz program hızlanır fakat tor network üzerinde iken aracı hızlandırmak çok mümkün değil. Ücretsiz günlük proxylerin de %95i çalışmadığından ücretli günlük proxy ile hızlandırılabilir
